#!/bin/bash

echo " "
echo " >>> INSTALLING TOOLS"
echo " "

apt-get -y install build-essential libssl-dev > /dev/null 2>&1

curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh -o installnvm.sh
bash installnvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
source $HOME/.nvm/nvm.sh

nvm --version
nvm ls -remote
nvm install node
nvm use node
echo "NODE VERSION"
nvm run node --version

echo "NVM VERSION"
nvm --version
echo " "
echo " "
